global:
  applicationName: example
  customerName: example
  image:
    defaultImageRepository: example

defaults:
  envFrom:
    - configMapRef:
        name: example
    - secretRef:
        name: app-secrets

argocd:
  disableProjectCreation: true
  projectOverride: "example-dev-example"

microservices:
  web:
    appLabel: web
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        memory: 1Gi
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8000
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 10
    readinessProbe:
      httpGet:
        path: /readiness
        port: 8000
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 10
    autoscaling:
      enabled: true
      minReplicas: 40
      maxReplicas: 100
      targetCPUUtilizationPercentage: 45
    service:
      enabled: true
      port: 80
      targetPort: 8080
      name: web

subCharts:
  redis:
    enabled: true
    name: redis # chart name
    chart: redis
    revision: '17.9.5'
    project: example-dev-example
    namespace: example
    values:
      image:
        repository: registry.gamewarden.io/example/redis
        version: 7.2.3
      persistence:
        enabled: true
      resources:
        requests:
          cpu: '0.04'
          memory: 85Mi
        limits:
          memory: 5Gi

  enabled: true
  data:
    SUBSCRIPTIONA: ''
    SUBSCRIPTIONB: ''
