---
apiVersion: v2
name: uchart
description: A universal application chart for gamewarden environments
type: application
version: 1.0.4
home: https:code.il2.gamewarden.io/gamewarden/tools/uchart
sources: [https://code.il2.gamewarden.io/gamewarden/tools/uchart]
icon: https://assets.website-files.com/6030224cd6bd6639e9d922c9/60e73ee577cd823be4d24834_GW-Icon.svg
appVersion: ''
maintainers:
  - email: anthony.butt@secondfront.com
    name: Anthony Butt
  - email: lucas.pick@secondfront.com
    name: Lucas Pick
annotations:
  schema: "https://schemas.gamewarden.io/schemas/helm/uchart.json"