---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: rbac values
templates:
  - uchart.yaml
values:
  - ../_values/rbac_values.yaml
tests:
  - it: default role and rolebinding should pass
    asserts:
      - hasDocuments:
          count: 3
      - documentIndex: &RoleDocument 1
        isKind:
          of: Role
      - documentIndex: *RoleDocument
        equal:
          path: rules[0].verbs
          value: ["get", "list"]

      - documentIndex: &BindingDocument 2
        isKind:
          of: RoleBinding
      - documentIndex: *BindingDocument
        equal:
          path: subjects[0].name
          value: RELEASE-NAME

  - it: custom role values should pass
    set:
      rbac:
        roles:
          customRole:
            type: ClusterRole
            rules:
              - apiGroups: ["*"]
                resources: ["*"]
                verbs: ["get", "list", "watch"]
    asserts:
      - hasDocuments:
          count: 4
      - documentIndex: &RoleDocument 1
        isKind:
          of: ClusterRole
      - documentIndex: *RoleDocument
        equal:
          path: rules[0].verbs
          value: ["get", "list", "watch"]