---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: Chart validations
templates:
  - entrypoint.yaml
values:
  - ../_values/workloads_main_default_container.yaml
tests:
  - it: advancedMounts invalid workload reference should fail
    set:
      volumes:
        data:
          type: configMap
          name: myConfigMap
          advancedMounts:
            test:
              main:
                - path: /data/config.yaml
                  readOnly: false
                  mountPropagation: HostToContainer
                  subPath: config.yaml
    asserts:
      - failedTemplate:
          errorMessage: "No enabled workload found with this id. (volume: 'data', workload: 'test')"
