{{- if and .Values.subCharts .Values.microservices }}
---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: "{{ .Values.global.customerName }}-{{ .Values.global.environment }}-{{ .Values.global.applicationName }}"
  namespace: argocd
spec:
  project: "{{ .Values.global.customerName }}-{{ .Values.global.environment }}-{{ .Values.global.applicationName }}"
  destination:
    namespace: {{ .Values.global.applicationName }}
    name: {{ .Values.global.destinationCluster }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - RespectIgnoreDifferences=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .;**/values.yaml
  revisionHistoryLimit: 3
  sources:
    - repoURL: registry.gamewarden.io/charts
      targetRevision: 1.0.1
      chart: uchart
      helm:
        values: |
          microservices:
          {{- toYaml  .Values.microservices | nindent 12 }}
          global:
          {{- toYaml  .Values.global | nindent 12 }}
          defaults:
          {{- toYaml  .Values.defaults | nindent 12 }}
          ciliumNetworkPolicies:
          {{- toYaml  .Values.ciliumNetworkPolicies | nindent 12 }}
{{- end }}
