{{- $defaultProject := printf "%s-%s-%s" (required "customerName is required" .Values.global.customerName) (required "environment is required" .Values.global.environment) (required "applicationName is required" .Values.global.applicationName) -}}
{{- if and .Values.subCharts .Values.microservices (not .Values.argocd.wrapperAppOff)}}
---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: "{{ .Values.global.customerName }}-{{ .Values.global.environment }}-{{ .Values.global.applicationName }}"
  namespace: argocd
{{-  if .Values.argocd.wrapperAppWave }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argocd.wrapperAppWave }}
{{- end }}
spec:
  project: "{{ default (printf "%s-%s-%s" .Values.global.customerName .Values.global.environment .Values.global.applicationName) .Values.argocd.projectOverride }}"
  destination:
    namespace: {{ .Values.global.applicationName }}
    name: {{ .Values.global.destinationCluster }}
  syncPolicy:
    {{- if .Values.argocd.wrapperSync }}
    automated:
      prune: true
      selfHeal: true
    {{- end }}
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - RespectIgnoreDifferences=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .;**/values.yaml
  revisionHistoryLimit: 3
  sources:
    - repoURL: registry.gamewarden.io/charts
      targetRevision: 1.0.4
      chart: uchart
      helm:
        values: |
          microservices:
          {{- toYaml  .Values.microservices | nindent 12 }}
          global:
          {{- toYaml  .Values.global | nindent 12 }}
          defaults:
          {{- toYaml  .Values.defaults | nindent 12 }}
          ciliumNetworkPolicies:
          {{- toYaml  .Values.ciliumNetworkPolicies | nindent 12 }}
          argocd:
          {{- toYaml  .Values.argocd | nindent 12 }}
          config:
          {{- toYaml  .Values.config | nindent 12 }}
{{- end }}
