---
global:
  applicationName: ice
  customerName: testapp
  impactLevel: il2
  environment: dev
  image:
    defaultImageRepository: testapp

microservices:
  backend:
    statefulset:
      enabled: true
    labels:
      protect: keycloak
    namespace: testapp
    resources:
      limits:
        cpu: 400m
        memory: 3Gi
      requests:
        cpu: 400m
        memory: 3Gi
    image:
      repository: registry.gamewarden.io/gw/keycloak
      tag: nightly
