global:
  applicationName: "ice"
  customerName: testapp
  impactLevel: il2
  environment: dev
  destinationCluster: multi-tenant-development-cluster
  image:
    defaultImageRepository: testapp


argocd:
#   wrapperAppOff: true
  wrapperAppWave: "1"
  wrapperSync: false
  # projectOverride: subChartProjectOverride
  serverSideApply: false
microservices:
  backend:
    statefulset:
      enabled: true
    labels:
      protect: keycloak
    namespace: testapp
    resources:
      limits:
        cpu: 400m
        memory: 3Gi
      requests:
        cpu: 400m
        memory: 3Gi
    image:
      repository: registry.gamewarden.io/gw/keycloak
      tag: "nightly"
subCharts:
  clamav:
    chartUrl: 'registry.gamewarden.io/charts'
    revision: 0.0.2
    wave: 3
    serverSideApply: false
    # project: overrideProjectName
  redis:
    revision: 17.9.5
    values:
      auth:
        existingSecret: "generated-secrets"
        existingSecretPasswordKey: "GENERATED_REDIS_PASSWORD"
  redis2:
    revision: 17.9.5
    name: redis
    values:
      nameOverride: redis2
      auth:
        existingSecret: "generated-secrets"
        existingSecretPasswordKey: "GENERATED_REDIS_PASSWORD"
  opensearch:
    revision: 2.19.0
    namespace: otherNamespace
    values:
      extraEnvs:
        - name: DISABLE_INSTALL_DEMO_CONFIG
          value: 'true'
        - name: DISABLE_SECURITY_PLUGIN
          value: 'true'
      global:
        dockerRegistry: registry.gamewarden.io
      image:
        repository: steelbank/cgr/opensearch
        tag: 2.13.0-r0
      imagePullSecrets:
        - name: private-registry
      persistence:
        image: steelbank/cgr/busybox
        imageTag: 1.36.1-r25
      replicas: 2
  justValuesUchart:
    values:
      simple: test
    sync: false
  uCharWithValuesRepo:
    values:
      test: values
    valuesRepo: https://github.com/second-front/example-values.git
    valuesRevision: main
    valueFiles:
    - $values/test-dev/base.yaml
    - $values/test-dev/dev.yaml
