---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: pvc values
templates:
  - entrypoint.yaml
values:
  - ../_values/workloads_main_default_container.yaml
tests:
  - it: default enabled should pass
    set:
      volumes.test:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
    asserts:
      - hasDocuments:
          count: 2
      - documentIndex: &PersistentVolumeClaimDocument 0
        isKind:
          of: PersistentVolumeClaim
      - documentIndex: *PersistentVolumeClaimDocument
        equal:
          path: metadata.name
          value: RELEASE-NAME-test

  - it: explicit enabled should pass
    set:
      volumes.test:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
    asserts:
      - hasDocuments:
          count: 2
      - documentIndex: &PersistentVolumeClaimDocument 0
        isKind:
          of: PersistentVolumeClaim
      - documentIndex: *PersistentVolumeClaimDocument
        equal:
          path: metadata.name
          value: RELEASE-NAME-test

  - it: explicit disabled
    set:
      volumes.test:
        enabled: false
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
    asserts:
      - hasDocuments:
          count: 1
      - documentIndex: &PersistentVolumeClaimDocument 0
        isKind:
          of: Deployment