{{- $ciliumNetworkPoliciesEnabled := .Values.ciliumNetworkPolicies.enabled }}
{{- if and $ciliumNetworkPoliciesEnabled (index .Values "minio-instance" "enabled") }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: ingress-allow-minio-operator
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels: {}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: minio-operator
    toPorts:
      - ports:
        - port: "9000"
          protocol: TCP
  {{- end }}