{{- if or (.Values.argocd.wrapperAppOff) ( not .Values.subCharts )}}
{{- range $msvc, $v := .Values.microservices}}
{{- with $ -}}

{{- if not (empty $v) }}

{{- if $v.cronjob }}
{{- if ($v.cronjob).enabled }}

{{/* Define image */}}
{{- $image := printf "%s:%s" $v.image.repository $v.image.tag -}}
{{ if $v.image.name }}
  {{- if .Values.global.image.defaultImageRegistry }}
    {{- if .Values.global.image.defaultImageRepository }}
      {{ $image = printf "%s/%s/%s:%s" .Values.global.image.defaultImageRegistry .Values.global.image.defaultImageRepository $v.image.name $v.image.tag }}
    {{- else }}
      {{ $image = printf "%s/%s:%s" .Values.global.image.defaultImageRegistry $v.image.name $v.image.tag }}
    {{- end }}
  {{- end }}
{{- else }}
  {{- if .Values.global.image.defaultImageRegistry }}
    {{- if .Values.global.image.defaultImageRepository }}
      {{ $image = printf "%s/%s/%s:%s" .Values.global.image.defaultImageRegistry .Values.global.image.defaultImageRepository $msvc $v.image.tag }}
    {{- else }}
      {{ $image = printf "%s/%s:%s" .Values.global.image.defaultImageRegistry $msvc $v.image.tag }}
    {{- end }}
  {{- end }}
  {{- if $v.image.repository }}
    {{ $image = printf "%s:%s" $v.image.repository $v.image.tag }}
  {{- end }}
{{ end }}

{{/* Variables */}}
{{- $completions := $v.completions | default 1 }}
{{- $parallelism := $v.parallelism | default 1 }}
{{- $restartPolicy := $v.restartPolicy | default "Never" }}
{{- $imagePullPolicy := $v.image.pullPolicy | default .Values.defaults.image.pullPolicy }}
{{- $imagePullSecrets := $v.imagePullSecrets | default .Values.defaults.imagePullSecrets }}
{{- $initContainers := $v.initContainers}}
{{- $resources := $v.resources | default .Values.defaults.resources }}
{{- $suspended := $v.suspended | default false }}
{{- $envs := $v.envs }}
{{- $extraEnvs := $v.extraEnvs | default .Values.defaults.extraEnvs }}

{{- $mergedEnvFrom := $v.envFrom | default (list) }}
{{- $defaultsEnvFrom := .Values.defaults.envFrom | default (list) }}
{{- range $defaultsEnvFrom }}
  {{- $mergedEnvFrom = append $mergedEnvFrom . }}
{{- end }}

{{- $labels := $v.labels }}
{{- $annotations := $v.annotations | default (dict) }}
{{- $podSecurityContext := $v.podSecurityContext | default .Values.defaults.podSecurityContext }}
{{- $securityContext := $v.securityContext | default .Values.defaults.securityContext }}
{{- $namespace := $v.namespace | default .Release.Namespace }}
{{- $command := $v.command }}
{{- $args := $v.args }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $msvc }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $msvc }}
    {{- include "universal-app-chart.labels" . | nindent 4 }}
    {{- if $labels -}} {{- toYaml $labels | nindent 4 }} {{- end }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  schedule: "{{ $v.cronjob.schedule }}"
  jobTemplate:
    spec:
      backoffLimit: {{ $v.cronjob.backoffLimit | default 4 }}
      completions: {{ $completions }}
      parallelism: {{ $parallelism }}
      template:
        spec:
          {{- with $imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $initContainers }}
          initContainers:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $podSecurityContext }}
          securityContext:
            {{- toYaml $podSecurityContext | nindent 12 }}
          {{- end }}
          restartPolicy: {{ $restartPolicy }}
          containers:
            - name: {{ $msvc }}
              image: {{ $image }}
              imagePullPolicy: {{ $imagePullPolicy }}
              {{- with $securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- if $v.command }}
              command:
                {{- toYaml $command | nindent 14 }}
              {{- end }}
              {{- if $v.args }}
              args:
                {{- toYaml $args | nindent 14 }}
              {{- end }}
              {{- if or ($mergedEnvFrom) ($v.config) ($v.secrets) }}
              envFrom:
              {{- toYaml $mergedEnvFrom | nindent 14 }}
              {{- end }}
              {{- with $resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
                {{- range $key, $value := $envs }}
                - name: {{ $key }}
                  value: {{ $value | toString | quote }}
                {{- end }}
                {{- range $extraEnvs }}
                - name: {{ .name | quote }}
                  {{- if .value }}
                  value: {{ with .value }}{{ tpl . $ | quote }}{{- end }}
                  {{- end -}}
                  {{- if .valueFrom }}
                  valueFrom:
                  {{- .valueFrom | toYaml | nindent 14 }}
                  {{- end -}}
                {{- end }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}
{{- end }}
{{- end }}
