{{- range $msvc, $v := .Values.microservices }}
{{- with $ -}}

{{- if not (empty $v) }}

{{- if $v.cronjob }}
{{- if ($v.cronjob).enabled }}
{{- $image := printf "%s:%s" $v.image.repository $v.image.tag }}
{{- if $v.image.name }}
  {{ $image = printf "%s/%s/%s:%s" .Values.global.image.defaultImageRegistry .Values.global.image.defaultImageRepository $v.image.name $v.image.tag }}
{{- else }}
  {{ $image = printf "%s/%s/%s:%s" .Values.global.image.defaultImageRegistry .Values.global.image.defaultImageRepository $msvc $v.image.tag }}
  {{ if $v.image.repository }}
  {{ $image = printf "%s:%s" $v.image.repository $v.image.tag }}
  {{ end }}
{{ end }}
{{- $completions := $v.completions | default 1 }}
{{- $parallelism := $v.parallelism | default 1 }}
{{- $restartPolicy := $v.restartPolicy | default "Never" }}
{{- $imagePullPolicy := $v.image.pullPolicy | default .Values.defaults.image.pullPolicy }}
{{- $suspended := $v.suspended | default false }}
{{- $envs := $v.envs }}
{{- $extraEnvs := $v.extraEnvs | default .Values.defaults.extraEnvs }}
{{- $labels := $v.labels }}
{{- $annotations := $v.annotations | default (dict) }}
{{- $securityContext := $v.securityContext | default (dict "capabilities" (dict "drop" (list "ALL"))) }}
{{- $namespace := $v.namespace | default .Release.Namespace }}
{{- $command := $v.command }}
{{- $args := $v.args }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $msvc }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $msvc }}
    {{- include "universal-app-chart.labels" . | nindent 4 }}
    {{- if $labels -}} {{- toYaml $labels | nindent 4 }} {{- end }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  schedule: "{{ $v.cronjob.schedule }}"
  jobTemplate:
    spec:
      backoffLimit: {{ $v.cronjob.backoffLimit | default 4 }}
      completions: {{ $completions }}
      parallelism: {{ $parallelism }}
      template:
        spec:
          restartPolicy: {{ $restartPolicy }}
          containers:
            - name: {{ $msvc }}
              image: {{ $image }}
              imagePullPolicy: {{ $imagePullPolicy }}
              {{- with $securityContext }}
              securityContext:
                {{- toYaml . | nindent 14 }}
              {{- end }}
              {{- if $v.command }}
              command:
                {{- toYaml $command | nindent 14 }}
              {{- end }}
              {{- if $v.args }}
              args:
                {{- toYaml $args | nindent 14 }}
              {{- end }}
              env:
                {{- range $key, $value := $envs }}
                - name: {{ $key }}
                  value: {{ $value | toString | quote }}
                {{- end }}
                {{- range $extraEnvs }}
                - name: {{ .name | quote }}
                  {{- if .value }}
                  value: {{ with .value }}{{ tpl . $ | quote }}{{- end }}
                  {{- end -}}
                  {{- if .valueFrom }}
                  valueFrom:
                  {{- .valueFrom | toYaml | nindent 14 }}
                  {{- end -}}
                {{- end }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}
{{- end }}
