{{- range $msvc, $v := .Values.microservices }}
{{- with $ -}}

{{- if not (empty $v) }}  # Check if the microservice values are not empty
{{- if $v.cronjob.enabled }}  # Check if the cronjob is enabled for the microservice
{{- $image := printf "%s:%s" $v.image.repository $v.image.tag }}
{{- if $v.image.name }}
  {{ $image = printf "%s/%s/%s:%s" .Values.global.image.defaultImageRegistry .Values.global.image.defaultImageRepository $v.image.name $v.image.tag }}
{{- else }}
  {{ $image = printf "%s/%s/%s:%s" .Values.global.image.defaultImageRegistry .Values.global.image.defaultImageRepository $msvc $v.image.tag }}
  {{ if $v.image.repository }}
  {{ $image = printf "%s:%s" $v.image.repository $v.image.tag }}
  {{ end }}  # End of the check if image.repository is set
{{ end }}  # End of the check if image.name is set

{{- $schedule := $v.cronjob.schedule | default .Values.defaults.cronjob.schedule }}
{{- $concurrencyPolicy := $v.cronjob.concurrencyPolicy | default "Forbid" }}
{{- $successfulJobsHistoryLimit := $v.cronjob.successfulJobsHistoryLimit | default 3 }}
{{- $failedJobsHistoryLimit := $v.cronjob.failedJobsHistoryLimit | default 1 }}
{{- $restartPolicy := $v.cronjob.restartPolicy | default "OnFailure" }}
{{- $imagePullPolicy := $v.image.pullPolicy | default .Values.defaults.image.pullPolicy }}
{{- $suspended := $v.cronjob.suspended | default false }}
{{- $envs := $v.envs }}
{{- $extraEnvs := $v.extraEnvs | default .Values.defaults.extraEnvs }}
{{- $labels := $v.labels }}
{{- $securityContext := $v.securityContext | default (dict "capabilities" (dict "drop" (list "ALL"))) }}
{{- $namespace := $v.namespace | default .Release.Namespace }}
{{- $command := $v.command | default .Values.defaults.command }}
{{- $args := $v.args | default .Values.defaults.args }}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $msvc }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $msvc }}
    {{- include "universal-app-chart.labels" . | nindent 4 }}
    {{- if $labels -}} {{- toYaml $labels | nindent 4 }} {{- end }}
spec:
  schedule: "{{ $schedule }}"
  concurrencyPolicy: {{ $concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ $successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ $failedJobsHistoryLimit }}
  suspend: {{ $suspended }}   # Added suspended support
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: {{ $restartPolicy }}
          containers:
            - name: {{ $msvc }}
              image: {{ $image }}
              imagePullPolicy: {{ $imagePullPolicy }}
              {{- with $securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
                - name: "POD_NAME"
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: "POD_NAMESPACE"
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: "NAMESPACE"
                  valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                {{- range $key, $value := $envs }}
                - name: {{ $key }}
                  value: {{ $value | toString | quote }}
                {{- end }}
                {{- range $extraEnvs }}
                - name: {{ .name | quote }}
                  {{- if .value }}
                  value: {{ with .value }}{{ tpl . $ | quote }}{{- end }}
                  {{- end -}}
                  {{- if .valueFrom }}
                  valueFrom:
                  {{- .valueFrom | toYaml | nindent 18 }}
                  {{- end -}}
                {{- end }}
              {{- if $command }}
              command:
                {{- toYaml $command | nindent 16 }}
              {{- end }}
              {{- if $args }}
              args:
                {{- toYaml $args | nindent 16 }}
              {{- end }}

{{- end }}  # End of cronjob enabled check
{{- end }}  # End of check if microservice values are not empty
{{- end }}  # End of the "with" block
{{- end }}
