{{- if or (.Values.argocd.wrapperAppOff) ( not .Values.subCharts ) }}
{{- range $msvc, $v := .Values.microservices}}
{{- with $ -}}
{{ if not (empty $v) }}
{{- if and (not $v.containers) (not $v.cronjob) (not $v.job) }}
{{- $statefulsetEnabled := (($v.statefulset).enabled) }}
{{- if not $statefulsetEnabled }}

{{/* Variables */}}
{{/* TODO: Turn this into ternary statement */}}
{{- $image := printf "%s:%s" $v.image.repository $v.image.tag -}}
{{ if $v.image.name }}
  {{ $image = printf "%s/%s/%s:%s" .Values.global.image.defaultImageRegistry .Values.global.image.defaultImageRepository $v.image.name $v.image.tag }}
{{- else }}
  {{ $image = printf "%s/%s/%s:%s" .Values.global.image.defaultImageRegistry .Values.global.image.defaultImageRepository $msvc $v.image.tag }}
  {{ if $v.image.repository }}
  {{ $image = printf "%s:%s" $v.image.repository $v.image.tag }}
  {{ end }}
{{ end }}
{{- $autoscalingEnabled := (($v.autoscaling).enabled) | default .Values.defaults.autoscaling.enabled }}
{{- $replicaCount := $v.replicaCount | default .Values.defaults.replicaCount }}
{{- $strategy := $v.strategy | default .Values.defaults.strategy }}
{{- $podAnnotations := $v.podAnnotations | default .Values.defaults.podAnnotations }}
{{- $imagePullSecrets := $v.imagePullSecrets | default .Values.defaults.imagePullSecrets }}
{{- $terminationGracePeriodSeconds := $v.terminationGracePeriodSeconds }}
{{- $podSecurityContext := $v.podSecurityContext | default .Values.defaults.podSecurityContext }}
{{- $createServiceAccount := (($v.serviceAccount).create) | default .Values.defaults.serviceAccount.create }}
{{- $serviceAccountName := (($v.serviceAccount).name) | default .Values.defaults.serviceAccount.name }}
{{- $securityContext := $v.securityContext | default .Values.defaults.securityContext }}
{{- $imagePullPolicy := (($v.image).pullPolicy) | default .Values.defaults.image.pullPolicy }}
{{- $envs := $v.envs }}
{{- $extraEnvs := $v.extraEnvs | default .Values.defaults.extraEnvs }}
{{- $extraVolumes := $v.volumes | default .Values.defaults.volumes }}
{{- $extraVolumeMounts := $v.volumeMounts | default .Values.defaults.volumeMounts }}

{{- $mergedEnvFrom := $v.envFrom | default (list) }}
{{- $defaultsEnvFrom := .Values.defaults.envFrom | default (list) }}
{{- range $defaultsEnvFrom }}
  {{- $mergedEnvFrom = append $mergedEnvFrom . }}
{{- end }}

{{- $serviceEnabled := (($v.service).enabled) | default .Values.defaults.service.enabled }}
{{- $resources := $v.resources | default .Values.defaults.resources }}
{{- $nodeSelector := $v.nodeSelector | default .Values.defaults.nodeSelector }}
{{- $affinity := $v.affinity | default .Values.defaults.affinity }}
{{- $topologySpreadConstraints := $v.topologySpreadConstraints }}
{{- $tolerations := $v.tolerations | default .Values.defaults.tolerations }}
{{- $namespace := $v.namespace | default .Release.Namespace }}
{{- $labels := $v.labels }}
{{- $selectorLabels := $v.selectorLabels }}
{{- $command := $v.command }}
{{- $appLabel := $v.appLabel | default $msvc }}
{{- $args := $v.args }}
{{- $workingDir := $v.workingDir }}
{{- $restartPolicy := $v.restartPolicy }}
{{- $livenessProbe := $v.livenessProbe }}
{{- $lifecycle := $v.lifecycle }}
{{- $readinessProbe := $v.readinessProbe }}
{{- $startupProbe := $v.startupProbe }}
{{- $initContainers := $v.initContainers}}
{{- $deploymentName := (($v.service).overrideName) | default $msvc }}


{{/* Service Vars */}}
{{- $type := (($v.service).type) | default .Values.defaults.service.type }}
{{- $port := (($v.service).port) | default .Values.defaults.service.port }}
{{- $targetPort := (($v.service).targetPort) | default .Values.defaults.service.targetPort }}
{{- $name := (($v.service).name) | default .Values.defaults.service.name }}
{{- $additionalPorts := (($v.service).additionalPorts) | default .Values.defaults.service.additionalPorts }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $appLabel }}
    {{- include "universal-app-chart.labels" . | nindent 4 }}
    {{- include "universal-app-chart.istioLabels" . | nindent 4 }}
    {{- if $labels -}} {{- toYaml $labels | nindent 4 }} {{- end }}
spec:
  revisionHistoryLimit: 3
  {{- if not $autoscalingEnabled }}
  replicas: {{ $replicaCount }}
  {{- end }}
  strategy:
    {{- toYaml $strategy | nindent 4 }}
  selector:
    matchLabels:
      app: {{ $appLabel }}
      {{- include "universal-app-chart.selectorLabels" . | nindent 6 }}
      {{- include "universal-app-chart.istioLabels" . | nindent 6 }}
      {{- if $selectorLabels -}} {{- toYaml $selectorLabels | nindent 6 }} {{- end }}
  template:
    metadata:
      {{- with $podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ $appLabel }}
        {{- include "universal-app-chart.selectorLabels" . | nindent 8 }}
        {{- include "universal-app-chart.istioLabels" . | nindent 8 }}
        {{- if $labels -}} {{- toYaml $labels | nindent 8 }} {{- end }}
        {{- if $selectorLabels -}} {{- toYaml $selectorLabels | nindent 8 }} {{- end }}
        {{- include "universal-app-chart.labels" . | nindent 8 }}
    spec:
      {{- with $imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "universal-app-chart.serviceAccountName" (list $createServiceAccount $serviceAccountName .) }}
    {{- if $initContainers }}
      initContainers:
      {{- with $initContainers -}}
        {{ tpl . $ | nindent 8 }}
      {{- end }}
    {{- end }}
      securityContext:
        {{- toYaml $podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ default 15 $terminationGracePeriodSeconds | int }}
      containers:
        - name: {{ $msvc }}
          securityContext:
            {{- toYaml $securityContext | nindent 12 }}
          image: {{ $image }}
          {{- if $workingDir }}
          workingDir: {{ $workingDir }}
          {{- end }}
          {{- with $livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $lifecycle }}
          lifecycle:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $startupProbe }}
          startupProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $command }}
          command:
            {{- toYaml $command | nindent 12 }}
          {{- end }}
          {{- if $args }}
          args:
            {{- toYaml $args | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ $imagePullPolicy }}
          {{- if $restartPolicy }}
          restartPolicy: {{ $restartPolicy }}
          {{- end -}}
          {{- if or ($mergedEnvFrom) ($v.config) ($v.secrets) }}
          envFrom:
          {{- toYaml $mergedEnvFrom | nindent 14 }}
          {{- end }}
          env:
            - name: "POD_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: "POD_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: "NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- range $key, $value := $envs }}
            - name: {{ $key }}
              value: {{ $value | toString | quote }}
            {{- end }}
            {{- range $extraEnvs }}
            - name: {{ .name | quote }}
              {{- if .value }}
              value: {{ with .value }}{{ tpl . $ | quote }}{{- end }}
              {{- end -}}
              {{- if .valueFrom }}
              valueFrom:
              {{- .valueFrom | toYaml | nindent 16 }}
              {{- end -}}
            {{- end }}
          {{- if $extraVolumeMounts }}
          volumeMounts:
          {{- range $extraVolumeMounts }}
            - name: {{ .name | quote }}
              mountPath: {{ .mountPath | toYaml }}
              {{- if .subPath }}
              subPath: {{ .subPath | toYaml }}
              {{- end -}}
          {{- end }}
          {{- end -}}
{{- if $serviceEnabled }}
          ports:
            - name: {{ $name }}
              containerPort: {{ $targetPort }}
              protocol: TCP
            {{- if $additionalPorts }}
            {{- range $additionalPorts }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol -}}
            {{- end }}
            {{- end }}
{{- end }}
          resources:
            {{- toYaml $resources | nindent 12 }}
      {{- with $nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $extraVolumes }}
      volumes:
        {{- with $extraVolumes -}}
        {{ tpl . $ | nindent 8 }}
        {{- end }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
