{{- if or (.Values.argocd.wrapperAppOff) ( not .Values.subCharts ) }}
{{- range $msvc, $v := .Values.microservices}}
{{- with $ }}
{{ if and (not (empty $v)) (not $v.containers) (not $v.cronjob) (not $v.job) (ne $v.enabled false) }}

{{/* Variables */}}
{{- $enabled := (($v.autoscaling).enabled) | default .Values.defaults.autoscaling.enabled }}
{{- $targetName := (($v.autoscaling).targetName) | default $msvc }}
{{- $minReplicas := (($v.autoscaling).minReplicas) | default .Values.defaults.autoscaling.minReplicas }}
{{- $maxReplicas := (($v.autoscaling).maxReplicas) | default .Values.defaults.autoscaling.maxReplicas }}
{{- $namespace := $v.namespace | default .Release.Namespace }}
{{- $targetCPUUtilizationPercentage := (($v.autoscaling).targetCPUUtilizationPercentage) }}
{{- $targetMemoryUtilizationPercentage := (($v.autoscaling).targetMemoryUtilizationPercentage) }}

{{- if $enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $msvc }}
  namespace: {{ $namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $targetName }}
  minReplicas: {{ $minReplicas }}
  maxReplicas: {{ $maxReplicas }}
  metrics:
    {{- if and $v.autoscaling.metrics (not (empty $v.autoscaling.metrics)) }}
      {{- range $m := $v.autoscaling.metrics }}
    - type: {{ $m.type }}
      {{- if eq $m.type "Resource" }}
      resource:
        name: {{ $m.resource.name }}
        target:
          type: {{ $m.resource.target.type }}
          {{- if $m.resource.target.averageUtilization }}
          averageUtilization: {{ $m.resource.target.averageUtilization }}
          {{- else if $m.resource.target.averageValue }}
          averageValue: {{ $m.resource.target.averageValue }}
          {{- end }}
      {{- else if eq $m.type "Pods" }}
      pods:
        metric:
          name: {{ $m.pods.metric.name }}
        target:
          type: {{ $m.pods.target.type }}
          averageValue: {{ $m.pods.target.averageValue }}
      {{- else if eq $m.type "Object" }}
      object:
        metric:
          name: {{ $m.object.metric.name }}
        describedObject:
          apiVersion: {{ $m.object.describedObject.apiVersion }}
          kind: {{ $m.object.describedObject.kind }}
          name: {{ $m.object.describedObject.name }}
        target:
          type: {{ $m.object.target.type }}
          value: {{ $m.object.target.value }}
      {{- else if eq $m.type "External" }}
      external:
        metric:
          name: {{ $m.external.metric.name }}
          {{- if $m.external.metric.selector }}
          selector:
            matchLabels:
              {{- range $key, $value := $m.external.metric.selector.matchLabels }}
              {{ $key }}: {{ $value | quote }}
              {{- end }}
          {{- end }}
        target:
          type: {{ $m.external.target.type }}
          {{- if $m.external.target.averageValue }}
          averageValue: {{ $m.external.target.averageValue }}
          {{- else if $m.external.target.value }}
          value: {{ $m.external.target.value }}
          {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- if $targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- if $targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $targetCPUUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
