{{- if or (.Values.argocd.wrapperAppOff) ( not .Values.subCharts ) }}
{{- range $msvc, $v := .Values.microservices }}
{{- with $ -}}

{{- if not (empty $v) }}
{{- if $v.job }}
{{- if ($v.job).enabled }}

{{/* Variables */}}
{{- $backoffLimit := $v.backoffLimit | default 6 }}
{{- $completions := $v.completions | default 1 }}
{{- $parallelism := $v.parallelism | default 1 }}
{{- $restartPolicy := $v.restartPolicy | default "Never" }}
{{- $imagePullPolicy := $v.image.pullPolicy | default .Values.defaults.image.pullPolicy }}
{{- $imagePullSecrets := $v.imagePullSecrets | default .Values.defaults.imagePullSecrets }}
{{- $initContainers := $v.initContainers}}
{{- $resources := $v.resources | default .Values.defaults.resources }}
{{- $suspended := $v.suspended | default false }}
{{- $envs := $v.envs }}
{{- $extraEnvs := $v.extraEnvs | default .Values.defaults.extraEnvs }}
{{- $extraVolumes := $v.volumes | default .Values.defaults.volumes }}
{{- $extraVolumeMounts := $v.volumeMounts | default .Values.defaults.volumeMounts }}

{{- $mergedEnvFrom := $v.envFrom | default (list) }}
{{- $defaultsEnvFrom := .Values.defaults.envFrom | default (list) }}
{{- range $defaultsEnvFrom }}
  {{- $mergedEnvFrom = append $mergedEnvFrom . }}
{{- end }}

{{- $labels := $v.labels }}
{{- $annotations := $v.annotations | default (dict) }}
{{- $securityContext := $v.securityContext | default (dict "capabilities" (dict "drop" (list "ALL"))) }}
{{- $namespace := $v.namespace | default .Release.Namespace }}
{{- $command := $v.command | default .Values.defaults.command }}
{{- $args := $v.args | default .Values.defaults.args }}

{{- if not $suspended }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $msvc }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $msvc }}
    {{- include "universal-app-chart.labels" . | nindent 4 }}
    {{- if $labels -}} {{- toYaml $labels | nindent 4 }} {{- end }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  completions: {{ $completions }}
  parallelism: {{ $parallelism }}
  backoffLimit: {{ $backoffLimit }}
  template:
    spec:
      {{- with $initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ $restartPolicy }}
      {{- with $imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $extraVolumes }}
      volumes:
        {{- with $extraVolumes -}}
        {{ tpl . $ | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ $msvc }}
          image: {{ include "uchart.image" (dict "msvc" $msvc "image" $v.image "Values" .Values) }}
          imagePullPolicy: {{ $imagePullPolicy }}
          {{- with $securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or ($mergedEnvFrom) ($v.config) ($v.secrets) }}
          envFrom:
          {{- toYaml $mergedEnvFrom | nindent 14 }}
          {{- end }}
          env:
            - name: "POD_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: "POD_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: "NAMESPACE"
              valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
            {{- range $key, $value := $envs }}
            - name: {{ $key }}
              value: {{ $value | toString | quote }}
            {{- end }}
            {{- range $extraEnvs }}
            - name: {{ .name | quote }}
              {{- if .value }}
              value: {{ with .value }}{{ tpl . $ | quote }}{{- end }}
              {{- end -}}
              {{- if .valueFrom }}
              valueFrom:
              {{- .valueFrom | toYaml | nindent 14 }}
              {{- end -}}
            {{- end }}
          {{- if $command }}
          command:
            {{- toYaml $command | nindent 12 }}
          {{- end }}
          {{- if $args }}
          args:
            {{- toYaml $args | nindent 12 }}
          {{- end }}
          {{- if $extraVolumeMounts }}
          volumeMounts:
          {{- range $extraVolumeMounts }}
            - name: {{ .name | quote }}
              mountPath: {{ .mountPath | toYaml }}
              {{- if .subPath }}
              subPath: {{ .subPath | toYaml }}
              {{- end -}}
          {{- end }}
          {{- end -}}

{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
