{{- range $msvc, $v := .Values.microservices }}
{{- with $v }}
  {{- if $v.config }}
    {{- range $configName, $configData := $v.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configName }}
  namespace: {{ $v.namespace | default $.Release.Namespace }}
data:
{{- range $key, $value := $configData }}
  {{- if contains "\n" $value }}
  {{ $key }}: |
{{- $value | nindent 4 }}
  {{- else }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}