{{- range $msvc, $v := .Values.microservices}}
{{- with $ }}
{{- if $v }}
{{/* Variables */}}
{{- $configMap := ($v.config).data }}
{{- $namespace := $v.namespace | default .Release.Namespace }}


{{- if $configMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $msvc }}-config
  namespace: {{ $namespace }}
  labels:
{{ include "universal-app-chart.labels" . | indent 4 }}
data:
{{- with $configMap }}
  {{- range $key, $value := . }}
  {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
