{{- if or (.Values.argocd.wrapperAppOff) ( not .Values.subCharts ) }}
{{- range $msvc, $v := .Values.microservices}}
{{- with $ -}}

{{ if not (empty $v) }}
{{- $statefulsetEnabled := (($v.statefulset).enabled) }}
{{- if not $statefulsetEnabled }}
{{- $daemonsetEnabled := (($v.daemonset).enabled) }}
{{- if $daemonsetEnabled }}
{{- if and $v.containers (ne $v.enabled false) }}
{{/* Variables */}}
{{- $annotations := $v.annotations | default (dict) }}
{{- $labels := $v.labels }}
{{- $namespace := $v.namespace | default .Release.Namespace }}
{{- $selectorLabels := $v.selectorLabels }}
{{- $serviceName := $v.serviceName | default $msvc }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $msvc }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $msvc }}
    {{- include "universal-app-chart.labels" . | nindent 4 }}
    {{- if $labels -}} {{- toYaml $labels | nindent 4 }} {{- end }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ $msvc }}
      {{- include "universal-app-chart.selectorLabels" . | nindent 6 }}
      {{- if $selectorLabels -}} {{- toYaml $selectorLabels | nindent 6 }} {{- end }}
  template:
    {{- include "containerTemplate" (dict "msvc" $msvc "image" $v.image "Values" .Values "global" $ "v" $v) | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
