{{- if or (.Values.argocd.wrapperAppOff) ( not .Values.subCharts ) }}
{{- range $msvc, $v := .Values.microservices}}
{{- with $ }}

{{- if $v }}
{{/* Variables */}}
{{- $serviceConfig := default dict $v.service }}
{{- $enabled := true }}
{{- if hasKey $serviceConfig "enabled" }}
  {{- if not $serviceConfig.enabled }}
    {{- $enabled = false }}
  {{- end }}
{{- end }}
{{ if and $enabled (not (empty $v)) (not $v.cronjob) (not $v.job) (ne $v.enabled false) }}

{{- $type := (($v.service).type) | default .Values.defaults.service.type }}
{{- $headless := (($v.service).headless) | default .Values.defaults.service.headless }}
{{- $port := (($v.service).port) | default .Values.defaults.service.port }}
{{- $targetPort := (($v.service).targetPort) | default .Values.defaults.service.targetPort }}
{{- $name := (($v.service).name) | default .Values.defaults.service.name }}
{{- $disablePortName := (($v.service).disablePortName) | default .Values.defaults.service.disablePortName }}
{{- $appProtocol := (($v.service).appProtocol) | default .Values.defaults.service.appProtocol }}
{{- $additionalPorts := (($v.service).additionalPorts) | default .Values.defaults.service.additionalPorts }}
{{- $appLabel := $v.appLabel | default $msvc }}
{{- $selectorLabels := $v.selectorLabels }}
{{- $sessionAffinity := (($v.service).sessionAffinity) }}
{{- $overrideName := (($v.service).overrideName) | default $msvc }}
{{- $namespace := $v.namespace | default .Release.Namespace }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $overrideName }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $appLabel }}
    {{- include "universal-app-chart.selectorLabels" . | nindent 4 }}
spec:
  type: {{ $type }}
  {{- if ($v.service).externalTrafficPolicy }}
  externalTrafficPolicy: {{ $v.service.externalTrafficPolicy }}
  {{- end }}
  {{- if ($v.service).internalTrafficPolicy }}
  internalTrafficPolicy: {{ $v.service.internalTrafficPolicy }}
  {{- end }}
{{- if $headless }}
  clusterIP: None
{{- end }}
  ports:
    - port: {{ $port }}
      targetPort: {{ $targetPort }}
      {{- if (($v.service).appProtocol) }}
      appProtocol: {{ $appProtocol }}
      {{- else }}
      protocol: TCP
      {{- end }}
      {{- if $disablePortName }}
      {{- else}}
      name: {{ $name }}
      {{- end }}
{{- if $additionalPorts }}
{{ toYaml $additionalPorts | indent 4 }}
{{- end }}
{{- if $sessionAffinity }}
  sessionAffinity: {{ toYaml $sessionAffinity }}
{{- end }}
  selector:
    app: {{ $appLabel }}
    {{- if $selectorLabels -}} {{- toYaml $selectorLabels | nindent 4 }} {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
