{{- if or (.Values.argocd.wrapperAppOff) ( not .Values.subCharts ) }}
{{- range $msvc, $v := .Values.microservices}}
{{- with $ -}}
{{- if $v }}
{{- if and (not $v.containers) (not $v.cronjob) (not $v.job) }}
{{/* Variables */}}
{{- $create := (($v.serviceAccount).create) | default .Values.defaults.serviceAccount.create }}
{{- $name := (($v.serviceAccount).name) | default .Values.defaults.serviceAccount.name}}
{{- $annotations := (($v.serviceAccount).annotations) | default .Values.defaults.serviceAccount.annotations }}
{{- $labels := (($v.serviceAccount).labels) | default .Values.defaults.serviceAccount.labels }}
{{- $rbacRules := (($v.rbac).rules) | default .Values.defaults.serviceAccount.labels }}
{{- $rbacLabels := (($v.rbac).labels) | default .Values.defaults.serviceAccount.labels }}
{{- $name := (($v.service).name) | default .Values.defaults.service.name }}
{{- $namespace := $v.namespace | default .Release.Namespace }}


{{- if $create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $msvc }}
  namespace: {{ $namespace }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
  {{- with $labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- include "universal-app-chart.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if $rbacRules }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $msvc }}
  namespace: {{ .Release.Namespace }}
{{- with $rbacLabels }}
  labels:
    {{- include "universal-app-chart.labels" . | nindent 4 }}
{{- end }}
{{- with $rbacRules }}
rules:
  {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $msvc }}
  labels:
    {{- include "universal-app-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $msvc }}
subjects:
  - kind: ServiceAccount
    name: {{ $msvc }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}

{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
